import { GraduationCap } from 'lucide-react'
import type { ReactNode } from 'react'

import { PeopleGroup } from '@/app/(user-scope)/(homepage)/icons/people-group'
import {
  AlarmClock,
  AlignDown,
  ArrowDownCircle,
  ArrowDownTrolley,
  ArrowUpCircle,
  ArrowUpTrolley,
  ArrowsDotsRotate,
  ArrowsMove,
  ArrowsUpRightDownLeft,
  Barcode,
  BeerFoamDrink,
  BellReminder,
  Bitcoin,
  BitcoinCircle,
  BoxFiling,
  BuildingColumn,
  BusinessBriefcase,
  BusinessSuitcase,
  CalendarDots,
  CalendarSchedule,
  CameraPhoto,
  CashBills,
  Chain,
  ClickSelect,
  Coding,
  Coins,
  Connection,
  Contract,
  Diagram,
  DiamondBanner,
  DiplomaCertificate,
  DollarSign,
  DotsHorizontal,
  DotsVertical,
  DownloadArrowDown,
  Envelope,
  EvenScale,
  ExportArrowRight,
  FeatherInk,
  FilingCabinet,
  Folders,
  FunnelSort,
  GamePlan,
  Gear,
  GiftBox,
  Graduate,
  GreenWater,
  GroupTeamCollective,
  HandHoldingGlobe,
  HandHoldingSeedling,
  HandHoldingWater,
  HeadGear,
  Heart,
  HeartBook,
  HeartPlant,
  HeartWater,
  Hierarchy,
  IdentificationCard,
  ImportArrowDownLeft,
  InfoCircle,
  InkBottle,
  LeafShield,
  LifeRing,
  LikeThumbsUpSticker,
  LinePresentation,
  Link,
  LinkChain,
  LinkSelect,
  LiquidBottle,
  ListChat,
  ListRight,
  MagnifyingGlass,
  MedalAchievement,
  MenuSquare,
  MessagesDots,
  MovementArrowsLeftRight,
  Oxygen,
  PaperAirplane,
  PaperStar,
  PencilEdit,
  PhonebookContacts,
  PinDestination,
  Plugin,
  PlusHeart,
  PresentBox,
  PuzzlePiece,
  QrCode,
  ReceiptDollar,
  ReceiptLines,
  ReplayArrowLeftRight,
  RotateArrowRight,
  RoundArrowUp,
  RoundArrows,
  RoundaboutArrows,
  Share,
  ShippingPackage,
  SolarPanelSun,
  SpeechPersonPodium,
  SpeechPodium,
  StarBanner,
  StarLightbulb,
  StarMedalAward,
  Statistics,
  Store,
  SupportRibbon,
  Tag,
  Target,
  TargetBullseye,
  ThermometerAlert,
  ThumbsUpLike,
  ThumbsUpLikes,
  TicketCoupon,
  UpLeftArrow,
  UpRightArrow,
  User,
  Users,
  WaterBottle,
  WaterLiquid,
  WaterRecycle,
  Wheelchair,
  WifiInternet,
  WinnerTrophy,
  WinningArrowUp
} from '@vectoricons/atlas-icons-react'

export const EDITABLE_ICON_FIELD_ICONS: Record<string, ReactNode> = {
  'arrow-down-circle': <ArrowDownCircle />,
  'arrow-up-circle': <ArrowUpCircle />,
  'arrows-up-right-down-left': <ArrowsUpRightDownLeft />,
  'beer-foam-drink': <BeerFoamDrink />,
  'diamond-banner': <DiamondBanner />,
  'gift-box': <GiftBox />,
  'green-water': <GreenWater />,
  'group-team-collective': <GroupTeamCollective />,
  graduate: <Graduate />,
  'leaf-shield': <LeafShield />,
  'liquid-bottle': <LiquidBottle />,
  'hand-holding-seedling': <HandHoldingSeedling />,
  'hand-holding-water': <HandHoldingWater />,
  heart: <Heart />,
  'heart-book': <HeartBook />,
  'heart-plant': <HeartPlant />,
  'heart-water': <HeartWater />,
  'hand-holding-globe': <HandHoldingGlobe />,
  'graduation-cap': <GraduationCap />,
  'round-arrows': <RoundArrows />,
  oxygen: <Oxygen />,
  'movement-arrows-left-right': <MovementArrowsLeftRight />,
  'plus-heart': <PlusHeart />,
  'speech-podium': <SpeechPodium />,
  'star-lightbulb': <StarLightbulb />,
  'star-medal-award': <StarMedalAward />,
  'solar-panel-sun': <SolarPanelSun />,
  'support-ribbon': <SupportRibbon />,
  'target-arrow-bullseye': <TargetBullseye />,
  'thermometer-alert': <ThermometerAlert />,
  'thumbs-up-like': <ThumbsUpLike />,
  'thumbs-up-likes': <ThumbsUpLikes />,
  'water-bottle': <WaterBottle />,
  'water-recycle': <WaterRecycle />,
  'water-liquid': <WaterLiquid />,
  'winning-arrow-up': <WinningArrowUp />,
  'wheel-chair': <Wheelchair />,
  'medal-achievement': <MedalAchievement />,
  contract: <Contract />,
  'dollar-sign': <DollarSign />,
  statistics: <Statistics />,
  'filing-cabinet': <FilingCabinet />,
  'arrow-down-trolley': <ArrowDownTrolley />,
  'arrow-up-trolley': <ArrowUpTrolley />,
  'business-briefcase': <BusinessBriefcase />,
  'even-scale': <EvenScale />,
  'building-column': <BuildingColumn />,
  barcode: <Barcode />,
  'receipt-dollar': <ReceiptDollar />,
  bitcoin: <Bitcoin />,
  'bitcoin-circle': <BitcoinCircle />,
  'box-filing': <BoxFiling />,
  'business-suitcase': <BusinessSuitcase />,
  'calendar-schedule': <CalendarSchedule />,
  'cash-bills': <CashBills />,
  coins: <Coins />,
  connection: <Connection />,
  'ticket-coupon': <TicketCoupon />,
  diagram: <Diagram />,
  hierarchy: <Hierarchy />,
  'feather-ink': <FeatherInk />,
  'receipt-lines': <ReceiptLines />,
  'head-gear': <HeadGear />,
  'identification-card': <IdentificationCard />,
  'ink-bottle': <InkBottle />,
  'life-ring': <LifeRing />,
  'shipping-package': <ShippingPackage />,
  'present-box': <PresentBox />,
  'puzzle-piece': <PuzzlePiece />,
  'line-presentation': <LinePresentation />,
  'qr-code': <QrCode />,
  store: <Store />,
  'game-plan': <GamePlan />,
  tag: <Tag />,
  target: <Target />,
  'messages-dots': <MessagesDots />,
  'list-chat': <ListChat />,
  'speech-person-podium': <SpeechPersonPodium />,
  'winner-trophy': <WinnerTrophy />,
  'star-banner': <StarBanner />,
  'paper-star': <PaperStar />,
  'diploma-certificate': <DiplomaCertificate />,
  'like-thumbs-up-sticker': <LikeThumbsUpSticker />,
  'roundabout-arrows': <RoundaboutArrows />,
  'round-arrow-up': <RoundArrowUp />,
  'export-arrow-right': <ExportArrowRight />,
  'download-arrow-down': <DownloadArrowDown />,
  'arrows-move': <ArrowsMove />,
  'import-arrow-down-left': <ImportArrowDownLeft />,
  'replay-arrow-left-right': <ReplayArrowLeftRight />,
  'rotate-arrow-right': <RotateArrowRight />,
  'up-left-arrow': <UpLeftArrow />,
  'up-right-arrow': <UpRightArrow />,
  'arrows-dots-rotate': <ArrowsDotsRotate />,
  user: <User />,
  'align-down': <AlignDown />,
  'alarm-clock': <AlarmClock />,
  'bell-reminder': <BellReminder />,
  'calendar-dots': <CalendarDots />,
  'camera-photo': <CameraPhoto />,
  'click-select': <ClickSelect />,
  coding: <Coding />,
  chain: <Chain />,
  'phonebook-contacts': <PhonebookContacts />,
  'dots-vertical': <DotsVertical />,
  'dots-horizontal': <DotsHorizontal />,
  'list-right': <ListRight />,
  'funnel-sort': <FunnelSort />,
  gear: <Gear />,
  folders: <Folders />,
  'info-circle': <InfoCircle />,
  'link-chain': <LinkChain />,
  'link-select': <LinkSelect />,
  link: <Link />,
  users: <Users />,
  'pin-destination': <PinDestination />,
  'menu-square': <MenuSquare />,
  envelope: <Envelope />,
  'paper-airplane': <PaperAirplane />,
  plugin: <Plugin />,
  'magnifying-glass': <MagnifyingGlass />,
  share: <Share />,
  'wifi-internet': <WifiInternet />,
  'pencil-edit': <PencilEdit />,
  'people-group': <PeopleGroup />
} as const

export type IconKey = keyof typeof EDITABLE_ICON_FIELD_ICONS
