import type { ReactNode } from 'react'

import {
  ArrowDownCircle,
  ArrowUpCircle,
  ArrowsUpRightDownLeft,
  BeerFoamDrink,
  DiamondBanner,
  GiftBox,
  Graduate,
  GreenWater,
  GroupTeamCollective,
  HandHoldingSeedling,
  HandHoldingWater,
  HeartBook,
  HeartPlant,
  HeartWater,
  LeafShield,
  LiquidBottle,
  MovementArrowsLeftRight,
  Oxygen,
  PlusHeart,
  RoundArrows,
  SolarPanelSun,
  SpeechPodium,
  StarLightbulb,
  StarMedalAward,
  SupportRibbon,
  TargetBullseye,
  ThermometerAlert,
  ThumbsUpLike,
  ThumbsUpLikes,
  WaterBottle,
  WaterLiquid,
  WaterRecycle,
  Wheelchair,
  WinningArrowUp,
  MedalAchievement,
  Contract,
  DollarSign,
  Statistics,
  FilingCabinet,
  ArrowDownTrolley,
  ArrowUpTrolley,
  BusinessBriefcase,
  EvenScale,
  BuildingColumn,
  Barcode,
  ReceiptDollar,
  Bitcoin,
  BitcoinCircle,
  BoxFiling,
  BusinessSuitcase,
  CalendarSchedule,
  CashBills,
  Coins,
  Connection,
  TicketCoupon,
  Diagram,
  Hierarchy,
  FeatherInk,
  ReceiptLines,
  HeadGear,
  IdentificationCard,
  InkBottle,
  LifeRing,
  ShippingPackage,
  PresentBox,
  PuzzlePiece,
  LinePresentation,
  QrCode,
  Store,
  GamePlan,
  Tag,
  Target,
  MessagesDots,
  ListChat,
} from '@vectoricons/atlas-icons-react'

export const EDITABLE_ICON_FIELD_ICONS: Record<string, ReactNode> = {
  'arrow-down-circle': <ArrowDownCircle />,
  'arrow-up-circle': <ArrowUpCircle />,
  'arrows-up-right-down-left': <ArrowsUpRightDownLeft />,
  'beer-foam-drink': <BeerFoamDrink />,
  'diamond-banner': <DiamondBanner />,
  'gift-box': <GiftBox />,
  'green-water': <GreenWater />,
  'group-team-collective': <GroupTeamCollective />,
  graduate: <Graduate />,
  'leaf-shield': <LeafShield />,
  'liquid-bottle': <LiquidBottle />,
  'hand-holding-seedling': <HandHoldingSeedling />,
  'hand-holding-water': <HandHoldingWater />,
  'heart-book': <HeartBook />,
  'heart-plant': <HeartPlant />,
  'heart-water': <HeartWater />,
  'round-arrows': <RoundArrows />,
  oxygen: <Oxygen />,
  'movement-arrows-left-right': <MovementArrowsLeftRight />,
  'plus-heart': <PlusHeart />,
  'speech-podium': <SpeechPodium />,
  'star-lightbulb': <StarLightbulb />,
  'star-medal-award': <StarMedalAward />,
  'solar-panel-sun': <SolarPanelSun />,
  'support-ribbon': <SupportRibbon />,
  'target-arrow-bullseye': <TargetBullseye />,
  'thermometer-alert': <ThermometerAlert />,
  'thumbs-up-like': <ThumbsUpLike />,
  'thumbs-up-likes': <ThumbsUpLikes />,
  'water-bottle': <WaterBottle />,
  'water-recycle': <WaterRecycle />,
  'water-liquid': <WaterLiquid />,
  'winning-arrow-up': <WinningArrowUp />,
  'wheel-chair': <Wheelchair />,
  'medal-achievement': <MedalAchievement />,
  contract: <Contract />,
  'dollar-sign': <DollarSign />,
  statistics: <Statistics />,
  'filing-cabinet': <FilingCabinet />,
  'arrow-down-trolley': <ArrowDownTrolley />,
  'arrow-up-trolley': <ArrowUpTrolley />,
  'business-briefcase': <BusinessBriefcase />,
  'even-scale': <EvenScale />,
  'building-column': <BuildingColumn />,
  barcode: <Barcode />,
  'receipt-dollar': <ReceiptDollar />,
  bitcoin: <Bitcoin />,
  'bitcoin-circle': <BitcoinCircle />,
  'box-filing': <BoxFiling />,
  'business-suitcase': <BusinessSuitcase />,
  'calendar-schedule': <CalendarSchedule />,
  'cash-bills': <CashBills />,
  coins: <Coins />,
  connection: <Connection />,
  'ticket-coupon': <TicketCoupon />,
  diagram: <Diagram />,
  hierarchy: <Hierarchy />,
  'feather-ink': <FeatherInk />,
  'receipt-lines': <ReceiptLines />,
  'head-gear': <HeadGear />,
  'identification-card': <IdentificationCard />,
  'ink-bottle': <InkBottle />,
  'life-ring': <LifeRing />,
  'shipping-package': <ShippingPackage />,
  'present-box': <PresentBox />,
  'puzzle-piece': <PuzzlePiece />,
  'line-presentation': <LinePresentation />,
  'qr-code': <QrCode />,
  store: <Store />,
  'game-plan': <GamePlan />,
  tag: <Tag />,
  target: <Target />,
  'messages-dots': <MessagesDots />,
  'list-chat': <ListChat />,
} as const

export type IconKey = keyof typeof EDITABLE_ICON_FIELD_ICONS
