import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

//@ts-ignore
import './globals.css'
import Footer from '../components/Footer'
import { Navbar } from '../components/Navbar'
import BootstrapClient from './BootstrapClient'

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] })
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        data-bs-theme="light"
      >
        <BootstrapClient />
        <Navbar />
        <main className="min-h-screen overflow-x-hidden bg-gray-50">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
