name: "(CI): Verify Build And Plan"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_URL: "https://capivara-solidaria.com.br"
      API_BASE_URL: "https://api.capivara-solidaria.com.br/"
      API_KEY: "dummy"
      NEXT_PUBLIC_POSTHOG_KEY: "dummy"
      NEXTAUTH_URL: "https://capivara-solidaria.com.br"
      NEXTAUTH_URL_INTERNAL: "https://capivara-solidaria.com.br"
      NEXTAUTH_SECRET: "dummy"
      GOOGLE_CLIENT_ID: "dummy"
      GOOGLE_CLIENT_SECRET: "dummy"
      JWT_SECRET: "dummy"
      OPENAI_API_KEY: "dummy"
      OPENAI_API_TOKEN_BASE_URL: "dummy"
      OPENAI_ORGANIZATION_ID: "dummy"
      OPENAI_PROJECT_ID: "dummy"
      WORDPRESS_BASE_URL: "https://public-api.wordpress.com/wp/v2/sites/frontendl2429yyi8vitingrsprojectsvercel.wordpress.com"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.12.0

      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.28.2

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run Unit Tests
        run: pnpm test:run

      - name: Run Build
        run: |
          pnpm run build
